### ISSUE TITLE
If you archive an message, it sends you to "archived" tab, but the link is not colored

### ISSUE THREAD

**Issue by raikasdev** [qlma/app#10]
![image](https://cdn.discordapp.com/attachments/567313617574166538/840641640573698118/Screenshot_from_2021-05-08_20-29-01.png)

**Comment by raikasdev** [comment]
This happens after you archive an message and it redirects you to here.

**Comment by jounile** [comment]
Know issue. The tab information is not altered when redirect happens. This feature is now using browsers local storage to store the tab. I was thinking that Django sessiln might be a better way to do it.

**Comment by jounile** [comment]
Archived tab highlighting is fixed. Now archived messages are also sorted so that last archived message shows on top.
Content HTML is rendered out.
