### ISSUE TITLE
Answering multiple times with duplicating HTTP request

### ISSUE THREAD

**Issue by raikasdev** [qlma/app#13]
By simply duplicating the HTTP Post request of voting duplicates the vote.
The app contains a lot of bugs with duplicating/modifying HTTP requests.

**Comment by jounile** [comment]
How do you duplicate the request? With Postman or something?
Now the vote is stored with voter id so multiple votes by a certain user can be detected in voting results.

**Comment by raikasdev** [comment]
> By simply duplicating the HTTP Post request of voting duplicates the vote.
> The app contains a lot of bugs with duplicating/modifying HTTP requests.

[https://qlma.herokuapp.com/polls/results/3/](https://qlma.herokuapp.com/polls/results/3/)
Not fixed.
